---
  - hosts: localhost
    gather_facts: no
    no_log: true   
    tasks: 
      - name: Add ssh key to agent
        block:
        - tempfile:
            state:  file
          register: tmp_key            
        - copy: 
            content: "{{ ssh_key }}"
            dest: "{{ tmp_key.path }}"
            mode: 0400
        - expect:
            command: ssh-add "{{ tmp_key.path }}"
            responses:
              (?i)Enter passphrase for*: "{{ ssh_key_password }}"
        - file:
            path: "{{ tmp_key.path }}"
            state: absent
