openapi: "3.0.0"
info:
  version: 0.1.0
  title: Platform Discovery Service API
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
paths:
  /discover:
    post:
      security:
        - apiKey: [ ]      
        - oauth2: [email] 
      summary: Automatic discovery and modeling of infrastructural resources. 
      operationId: discover
      requestBody:
        description: Endpoint information and access credentials.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DiscoveryInput"
      responses:
        200:
          description: The discovery was successful.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DiscoveryOutput"
        400:
          description: Malformed discovery request.
          content:
            application/json:
              schema:
                type: string                  
        401:
          description: Unauthorized request for discovery.
          content:
            application/json:
              schema:
                type: string                   
        500:
          description: There was an error during discovery.
          content:
            application/json:
              schema:
                type: string  
  /update:
    post:
      security:
        - apiKey: [ ]      
        - oauth2: [email] 
      summary: Automatic discovery and update resource database. 
      operationId: discover_update
      requestBody:
        description: Endpoint information and access credentials.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateInput"
      responses:
        200:
          description: The update was successful.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateOutput"
        400:
          description: Malformed update request.
          content:
            application/json:
              schema:
                type: string                  
        401:
          description: Unauthorized request for update.
          content:
            application/json:
              schema:
                type: string                   
        500:
          description: There was an error during update.
          content:
            application/json:
              schema:
                type: string                  
       
 
components:
  schemas:
    DiscoveryInput:
      description: Endpoint information and access credentials provided as inputs.
      type: object
      required:
        - inputs
        - namespace
        - platform_type
      properties:
        inputs:
          type: object
        namespace:
          description: The namespace name in which resource and application models will be saved.
          type: string          
        platform_type:
          $ref: "#/components/schemas/PlatformType"
    DiscoveryOutput:
      description: Result of discovery.
      type: object
      required:
        - timestamp
        - service_template
      properties:
        timestamp:
          description: An ISO8601 timestamp of the discovery.
          type: string
        service_template:
          description: The service template with discovered info.
          type: object
    PlatformType:
      type: string
      enum:
        - slurm
        - torque
        - openstack
        - aws          
        - kubernetes       
    UpdateInput:
      description: Endpoint information and access credentials provided as inputs.
      type: object
      required:
        - inputs
        - namespace
        - platform_type
      properties:
        inputs:
          type: object
        namespace:
          description: The namespace name in which resource and application models will be saved.
          type: string          
        aadm_uri:
          description: AADM URI to update (optional).
          type: string
        rm_uri:
          description: RM URI to update (optional).
          type: string          
        platform_type:
          $ref: "#/components/schemas/PlatformType"
    UpdateOutput:
      description: An invocation of the deployment.
      type: object
      properties:
        aadm_uri:
          description: AADM URI that stores updated info.
          type: string
        rm_uri:
          description: RM URI that stores updated info.
          type: string

  securitySchemes:
    apiKey:
      type: apiKey
      x-apikeyInfoFunc: pds.api.controllers.security.check_api_key
      name: X-API-Key
      in: header  
    oauth2:
      flows:
        password: 
          tokenUrl: http://keycloak:8080/auth/realms/SODALITE/protocol/openid-connect/token
          scopes:
            email: Email of the user accessing the service.
      type: oauth2
      x-tokenInfoFunc: pds.api.controllers.security.token_info
      x-scopeValidateFunc: pds.api.controllers.security.validate_scope      
