---
  - hosts: localhost
    gather_facts: no
    tasks:
      - name: >
          Create temporary inventory for wm, 
          since opera requires internal envvars to access the target. 
          Need more examples to access static nodes without specifying them in the inventory file
        add_host:
          name: wm
          groups: wm
          ansible_host: "{{ wm_public_address }}"
          ansible_user: "{{ wm_username }}"
          #ansible_ssh_private_key_file: "{{ wm_keypath }}"
          ansible_ssh_common_args: >
            -o IdentitiesOnly=no
            -o BatchMode=yes
            -o UserKnownHostsFile=/dev/null
            -o StrictHostKeyChecking=no
  
  - hosts: wm
    gather_facts: no
    tasks:
      - name: Get torque node info
        sodalite.hpc.torque_node_info:
        register: node_info

      - name: Get torque queue info
        sodalite.hpc.torque_queue_info:
        register: queue_info

      - name: Set attribute
        set_stats:
          data:
            node_info: "{{ node_info }}"      
            queue_info: "{{ queue_info }}"    