### REQUIRED

# The namespace of the collection. This can be a company/brand/organization or product namespace under which all
# content lives. May only contain alphanumeric lowercase characters and underscores. Namespaces cannot start with
# underscores or numbers and cannot contain consecutive underscores
namespace: sodalite

# The name of the collection. Has the same character restrictions as 'namespace'
name: hpc

# The version of the collection. Must be compatible with semantic versioning
version: 1.0.0

readme: README.md

authors:
- Alexander Maslennikov <alexander.maslennikov@xlab.si>

tags:
  - sodalite
  - torque
  - slurm
  - discovery
  - hpc

license_file: COPYING
description: Modules for discovering HPC resources. Modules for managing HPC jobs.

repository: https://github.com/SODALITE-EU/platform-discovery-service
